apiVersion: v1
kind: Service
metadata:
  name: dboctav
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: DB
  ports:
    - targetPort: 3306
      port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DB
  template:
    metadata:
      labels:
        app: DB
    spec:
      containers:
      - name: dboctav
        image: petreocty1998/octav_rep:dbster
        ports:
        - containerPort: 3306
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
