apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: DB
spec:
  type: ClusterIP
  selector:
    app: MYSQL
  ports:
    - targetPort: 3306
      port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: DB
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MYSQL
  template:
    metadata:
      labels:
        app: MYSQL
    spec:
      containers:
      - name: db-container
        image: mysql:5.7 #petreocty1998/octav_rep:dbster
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sed -i /docker-entrypoint-initdb.d/planetickets.sql -e 's/utf8mb4_0900_ai_ci/utf8mb4_unicode_ci/g'"]
          preStop:
            exec:
              command: ["/bin/sh","-c","mysqldump -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > /docker-entrypoint-initdb.d/planetickets.sql"]
        ports:
        - containerPort: 3306
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
               name: db-configmap
               key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mysql-storage
        azureFile:
          secretName: azure-db-secret
          shareName: dboctav
          readOnly: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  labels:
    app: DB
data:
  MYSQL_DATABASE: "planetickets"
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_ROOT_PASSWORD: "test"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-db-secret
  labels:
    app: DB
type: Opaque
data:
  azurestorageaccountname: cGxhbmV0aWNrZXRz
  azurestorageaccountkey: dG92Q3d1QWJCT3RmaDNtZ1FZV05mRmIzZ2UramZDR2dBMnV2VngxNVpmZlo5L2FQcGN0L3JkWHRPNlNKSU1yRlY2RDJSYkMvaDlJVnBYNnlOazlvSUE9PQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    usage: azureDB-storage
    app: DB
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-db-secret
    shareName: dboctav
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: DB
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      usage: azureDB-storage
---




