apiVersion: v1
kind: ConfigMap
metadata:
  name: ap-configmap
data:
  MYSQL_HOST: "dboctav"
  MYSQL_USER: "test"
  MYSQL_PASS: "test"
  MYSQL_DB: "planetickets"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  MYSQL_DATABASE: "planetickets"
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_ROOT_PASSWORD: "test"
