# construiește imaginea pornind de la o imagine existentă numita ”centos”, versiunea ”latest”
FROM centos:latest

# stabilește cine se ocupă de imagine
MANTAINER petreoctavian

# setarea varibilelor de mediu
ENV key value

# execută o comandă în timpul construirii imaginii
RUN yum install git

# din acest punct, orice comandă ulterioară va fi executată sub user-ul ”centos”
USER centos

# atunci când vom porni containerul, va fi executată comanda /usr/sbin/haproxy cu parametrii respectivi
ENTRYPOINT /usr/sbin/haproxy -f /etc/haproxy.cfg

# copiază haproxy.cfg de pe host în container la locația /etc/haproxy.cfg
COPY haproxy.cfg /etc/haproxy.cfg

# adaugă conținutul url în container la locația /tmp/resources
ADD http://site.com/resources /tmp/resources

# crearea unui volum persistent la locația /data/persistent din cadrul containerului
VOLUME /data/persistent

# publică doar la nivel informativ porturile pe care există aplicații în container
EXPOSE 80/tcp
